- name: Install the required packages
  npm:
    name: yarn
    global: yes
  tags:
    - install
    - node
  loop:
    - yarn
    - eslint
    - prettier
    - nodemon
    - typescript
    - typescript-language-server
    - pm2
    - ts-node