# - name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
#   become: true
#   apt_repository:
#    repo: ppa:kdenlive/kdenlive-stable
#    state: present
#    update_cache: True
#   tags:
#     - install
#     - productivity

# - name: shutter ppa (ppa:linuxuprising/shutter)
#   become: true
#   apt_repository:
#    repo: ppa:linuxuprising/shutter
#    state: present
#    update_cache: True
#   tags:
#     - install
#     - productivity

- name: Install Neovim on the machine
  become: true
  apt:
    name: neovim
  tags:
    - install
    - productivity

- name: Install zoxide
  ansible.builtin.shell: >
    curl -sS https://webinstall.dev/zoxide | bash
  tags:
    - install
    - productivity

- name: Install all the other productivity software solutions
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "kdenlive", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "shutter" ]
  tags:
    - install
    - productivity