- name: Ensure .ssh key exists for github
  file:
    dest: "{{ github_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key for github
  copy:
    src: "{{ github_source_key }}"
    dest: "{{ github_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public for github
  copy:
    src: "{{ github_source_key }}.pub"
    dest: "{{ github_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
- name: Set authorized key took from file for github
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
